<?php

namespace App\Services\Growth\Community2026;

class ForumDiscoveryProvider implements CommunityDiscoveryProvider
{
    public function subtype(): string
    {
        return 'forum';
    }

    public function urls(): array
    {
        return [
            'https://forum.v-strom.nl',
            'https://www.motor-forum.nl',
            'https://www.autoweek.nl/forum',
            'https://www.problemcar.nl',
            'https://www.carclean.com/nl/forum',
            'https://www.carclean.nl/forum',
            'https://www.citroen-forum.nl',
            'https://www.peugeotforum.nl',
            'https://www.renaultforum.nl',
            'https://www.saabforum.nl',
            'https://www.volvo-forum.nl',
            'https://www.volvo850forum.nl',
            'https://www.volvo40forum.nl',
            'https://www.audiforum.nl',
            'https://www.vwforum.nl',
            'https://www.golfgtiforum.nl',
            'https://www.bmwdriversforum.nl',
            'https://www.bimmerportal.nl',
            'https://www.mercedesforum.nl',
            'https://www.porscheforum.nl',
            'https://www.jaguarforum.nl',
            'https://www.landroverforum.nl',
            'https://www.alfaromeo156club.nl/forum',
            'https://www.fiatforum.nl',
            'https://www.fordforum.nl',
            'https://www.opel-forum.nl',
            'https://www.skodaforum.nl',
            'https://www.seat-online.nl',
            'https://www.daciaforum.nl',
            'https://www.hyundaiforum.nl',
            'https://www.kiaclub.nl/forum',
            'https://www.toyotahybrideforum.nl',
            'https://www.toyotaforum.nl',
            'https://www.hondaforum.nl',
            'https://www.mazdaforum.nl',
            'https://www.mx5forum.nl',
            'https://www.subaruclub.nl/forum',
            'https://www.suzukiclubnederland.nl/forum',
            'https://www.nissanclub.nl/forum',
            'https://www.camperforum.nl',
            'https://www.camperpunt.nl/forum',
            'https://www.bus-forum.nl',
            'https://www.buscamperforum.nl',
            'https://www.caravan-forum.nl',
            'https://www.campingforum.nl',
            'https://www.oldtimerforum.nl',
            'https://www.bromfietsforum.nl',
            'https://www.zundappforum.nl',
            'https://www.puchforum.nl',
            'https://www.kreidlerforum.nl',
            'https://www.solexforum.nl',
            'https://www.vespaforum.nl',
            'https://www.scooterforum.net',
            'https://www.chopperforum.nl',
            'https://www.custommotorforum.nl',
            'https://www.motor-forum.nl/forums/harley-davidson.79',
            'https://www.motor-forum.nl/forums/bmw.48',
            'https://www.motor-forum.nl/forums/ducati.52',
            'https://www.motor-forum.nl/forums/honda.55',
            'https://www.motor-forum.nl/forums/yamaha.65',
            'https://www.motor-forum.nl/forums/suzuki.62',
            'https://www.motor-forum.nl/forums/kawasaki.57',
            'https://www.motor-forum.nl/forums/aprilia.45',
            'https://www.motor-forum.nl/forums/triumph.64',
            'https://www.motor-forum.nl/forums/moto-guzzi.59',
            'https://www.motor-forum.nl/forums/klassiekers.88',
            'https://www.motor-forum.nl/forums/trackdays.93',
            'https://www.driving-fun.com/forum',
            'https://forum.driving-fun.com',
            'https://www.racefreaks.nl/forum',
            'https://www.rallysport.nl/forum',
            'https://www.4x4forum.nl',
            'https://www.landcruiserclub.nl/forum',
            'https://www.jeepforum.nl',
            'https://www.teslaforum.nl',
            'https://www.evforum.nl',
            'https://www.elektrischrijdenforum.nl',
            'https://www.laaddraad.nl',
            'https://www.mobiliteitsforum.nl',
        ];
    }
}
